version: "3.8"
services:
  polkabtc:
    image: "registry.gitlab.com/interlay/btc-parachain:dev"
    command:
      - btc-parachain
      - --ws-external
      - --dev
    network_mode: "host"
    ports:
      - "9944:9944"
  staked-relayer:
    image: "registry.gitlab.com/interlay/polkabtc-clients:staked-relayer-dev"
    command:
      - /bin/sh
      - -c
      - |
        echo "Sleeping..."
        sleep 5
        staked-relayer --http-addr '[::0]:3030' --polka-btc-url 'ws://localhost:9944'
    environment:
      BITCOIN_RPC_URL: http://localhost:18332
      BITCOIN_RPC_USER: rpcuser
      BITCOIN_RPC_PASS: rpcpassword
      RUST_LOG: info
    network_mode: "host"
    ports:
      - "3030:3030"
  oracle:
    image: "registry.gitlab.com/interlay/polkabtc-clients:oracle-dev"
    command:
      - /bin/sh
      - -c
      - |
        echo "Sleeping..."
        sleep 5
        oracle --polka-btc-url 'ws://polkabtc:9944'
    environment:
      RUST_LOG: info
    network_mode: "host"
  vault:
    image: "registry.gitlab.com/interlay/polkabtc-clients:vault-dev"
    command:
      - /bin/sh
      - -c
      - |
        echo "Sleeping..."
        sleep 5
        vault --http-addr '[::0]:3031' --polka-btc-url 'ws://localhost:9944'
    environment:
      BITCOIN_RPC_URL: http://localhost:18332
      BITCOIN_RPC_USER: rpcuser
      BITCOIN_RPC_PASS: rpcpassword
      RUST_LOG: info
    network_mode: "host"
    ports:
      - "3031:3031"